<section id="footer">
    <footer>
        <h2>Links and Contact</h2>
        <nav>
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="about.php">About us</a></li>
                <li><a href="jobs.php">Job Description</a></li>
                <li><a href="apply.php">Apply</a></li>
            </ul>
        </nav>
        <p> Contact JigSaw Email: </p><a class="link" href="mailto:info@jigsaw.com.au">info@jigsaw.com.au</a>
        <p>Jira Tool used located: <a class="link" href="https://project1webtech.atlassian.net/jira/software/projects/SCRUM/boards/1?atlOrigin=eyJpIjoiMTNjNTIzYzM2MTJiNDRiMjgzOWRmYTI1NGE0NDg3Y2EiLCJwIjoiaiJ9" target="_blank">Jira Link</a></p>
        <p> &copy; 2025 Swinburne Students of Web Developent Project <a href="about.php">Located Here</a></p>
        <p>GitHub Repository Link <a href="https://github.com/JoshThai/project1.git" target="_blank">project1</a></p>
    </footer>
</section>