<section id="header">
    <header>
        <div class="logo-title-container"> <a href="index.php"><img id="logo" src="images/groupProjectLogo_updated.png" alt="JigSaw logo" width="200" height="100"></a>
            <h1>Jigsaw security</h1>
        </div>
        <nav>
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="jobs.php">Job Description</a></li>
                <li><a href="apply.php">Apply</a></li>
                <li><a href="about.php">About us</a></li>
                <li><a href="login.php">Manager</a></li>              
                <li><a class="link" href="mailto:info@jigsaw.com.au">info@jigsaw.com.au</a></li>
                
            </ul>
        </nav>
    </header>
</section>